const projects = [
  {
    "name": "Anvilogic",
    "slug": "anvilogic",
    "previewImage": "./images/anvilogic-preview.png",
    "description": "Anvilogic offers the only multi-SIEM detection platform approach to threat detection and response that helps you build the detections you want across the data platforms you choose. Anvilogic simplifies detection engineering, closes critical detection gaps, tracks progress against MITRE, and leverages AI to automate detection maintenance, all in one streamlined platform.",
    "tags": ["React", "Styled Components", "Material UI", "Redux", "Amazon S3"],
    "link": {
      "image": "./images/anvilogic-link.gif",
      "title": "Build Detections You Want, Where You Want | Anvilogic",
      "description": "Anvilogic can help streamline detection engineering and unify your SIEM and security data lake to cut costs and close detection gaps across multiple data platforms.",
      "url": "anvilogic.com",
    },
    "screenshot": "./images/anvilogic-screenshot.png",
  },
  {
    "name": "Zenport",
    "slug": "zenport",
    "previewImage": "./images/zenport-preview.png",
    "description": "As global supply chains grow complex, ZENPORT connects scattered and fragmented data sets across processes and organizations. Beyond Excel, ZENPORT streamlines operations and accelerates global initiatives. Where data flows meet, ZENPORT is a new experience in global supply chain management.",
    "tags": ["React", "Next.js", "Figma"],
    "link": {
      "image": "./images/zenport-link.png",
      "title": "ZENPORT | グローバルサプライチェーンの 全データを一括管理",
      "description": "グローバルサプライチェーンの全データを一括管理。ZENPORTは、プロセス・組織を超え、グローバルサプライチェーンの全データをつなぎ、新たな商物流の立上げや資産効率改善などでグローバルにビジネスを加速します。",
      "url": "zenport.io",
    },
    "screenshot": "./images/zenport-screenshot.png",
  },
  {
    "name": "Schubas Tavern | Lincoln Hall",
    "slug": "lh-st",
    "previewImage": "./images/lh-st-preview.png",
    "description": "Schubas and Lincoln Hall are sister venues located in Chicago's Lakeview and Lincoln Park neighborhoods. Lincoln Hall is a larger venue, with a capacity of 507, while Schubas Tavern is a smaller, more intimate space.",
    "tags": ["WordPress", "Bootstrap", "jQuery", "Wireframes"],
    "link": {
      "image": "./images/lh-st-link.png",
      "title": "Schubas Tavern || Lincoln Hall - Chicago, IL",
      "description": "Schubas and Lincoln Hall are sister venues located in Chicago’s Lakeview and Lincoln Park neighborhoods. All are welcome.",
      "url": "lh-st.com",
    },
    "screenshot": "./images/lh-st-screenshot.png",
  },
  {
    "name": "Linescape",
    "slug": "linescape",
    "previewImage": "./images/linescape-preview.png",
    "description": "Whether you're planning container bookings or analyzing vessel movements, Linescape has the most comprehensive sailing schedule database. Complete, accurate and updated continuously, our schedule data is available to logistics professionals - anytime, anywhere.",
    "tags": ["Angular", "Stripe", "Amazon S3", "AWS CloudFront", "Wireframes"],
    "link": {
      "image": "./images/linescape-link.png",
      "title": "Linescape - Ocean Container Shipping Schedules",
      "description": "Linescape has the most comprehensive sailing schedule database. Complete, accurate and updated continuously, our schedule data is available to logistics...",
      "url": "linescape.com",
    },
    "screenshot": "./images/linescape-screenshot.png",
  },
  {
    "name": "",
    "slug": "",
    "previewImage": "./images/-preview.png",
    "description": "",
    "tags": [],
    "link": {
      "image": "./images/-link.png",
      "title": "",
      "description": "",
      "url": "",
    },
    "screenshot": "./images/-screenshot.png",
  },
  {
    "name": "",
    "slug": "",
    "previewImage": "./images/-preview.png",
    "description": "",
    "tags": [],
    "link": {
      "image": "./images/-link.png",
      "title": "",
      "description": "",
      "url": "",
    },
    "screenshot": "./images/-screenshot.png",
  },
  {
    "name": "",
    "slug": "",
    "previewImage": "./images/-preview.png",
    "description": "",
    "tags": [],
    "link": {
      "image": "./images/-link.png",
      "title": "",
      "description": "",
      "url": "",
    },
    "screenshot": "./images/-screenshot.png",
  },
]

export default projects